### ISSUE TITLE
Can not install  pg_qualstats on ubuntu.

### ISSUE THREAD

**Issue by darshansh** [powa-team/pg_qualstats#27]
Hello, 
on my ubuntu machine postgresql 10 is installed. I tried to install pg_qualstats  using below url. 
https://powa.readthedocs.io/en/latest/components/stats_extensions/pg_qualstats.html

I got below error. 
pg_qualstats.c:27:22: fatal error: postgres.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'pg_qualstats.o' failed
make: *** [pg_qualstats.o] Error 1
Could any one suggest what to do in this case ?

**Comment by rjuju** [comment]
Hello,

The installation part starts with various requirements documented in the quickstart.  Did you install the `postgresql-server-dev-10` package as mentioned in https://powa.readthedocs.io/en/latest/quickstart.html#installation-of-the-postgresql-extensions?

**Comment by darshansh** [comment]
Thanks Julien Rouhaud. 
Your comments help me. I configured it and now it is working ok.
