### ISSUE TITLE
Build error on RHEL 7 *and* PostgreSQL <= 11

### ISSUE THREAD

**Issue by devrimgunduz** [powa-team/pg_qualstats#28]
Hi,

2.0.0 fails to build on RHEL7 against PostgreSQL <= 11. This does not happen on other distros and PostgreSQL versions. RHEL  and PG12 builds fine.

gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 

Here is the error:

+ /usr/bin/make USE_PGXS=1 -j4
pg_qualstats.c: In function 'pgqs_entry_err_estim':
pg_qualstats.c:921:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < 2; i++)
  ^
pg_qualstats.c:921:2: note: use option -std=c99 or -std=gnu99 to compile your code
pg_qualstats.c: In function 'pgqs_process_opexpr':
pg_qualstats.c:1519:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (int step = 0; step < 2; step++)
   ^
pg_qualstats.c: In function 'pg_qualstats_common':
pg_qualstats.c:2002:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (int j = 0; j < 2; j++)
   ^
make[1]: *** [pg_qualstats.o] Error 1
make[1]: *** Waiting for unfinished jobs....
error: Bad exit status from /var/tmp/rpm-tmp.CK05mX 

Can you please take a look?

Regards, Devrim

**Comment by rjuju** [comment]
Hi @devrimgunduz 

FTR I also noticed that recently at work, but as this was failing on PG12+ too I was suspecting some build issue that would need to be investigated rather than changing it upstream.

I just pushed https://github.com/powa-team/pg_qualstats/commit/9f2c01afb35699c5ddbf31ab1f69501bce2fa9f4.  Can you confirm that this fixes the build? If yes I'll release 2.0.1.

**Comment by devrimgunduz** [comment]
Hi @rjuju ,

Thanks for the quick response! Tested the patch, and it works --and also it does not break other distros.

I'll wait for 2.0.1 for the updated packages.

Regards, Devrim

**Comment by rjuju** [comment]
Thanks a lot for confirming.  I just published 2.0.1!

**Comment by rjuju** [comment]
Make sure that you use commit https://github.com/powa-team/pg_qualstats/commit/c0590e39f40f10c6c5b46133952d1346a4858088, I previously failed to add the modified sql script, sorry for the inconvenience :/
