### ISSUE TITLE
pg_qualstats_indexes usage post 2.0

### ISSUE THREAD

**Issue by rom1dep** [powa-team/pg_qualstats#31]
I was trying to use pg_qualstats for the first time, and naively ran `select * from pg_qualstats_indexes` following the instructions in the readme, which led to an error.

Could it be that the `pg_qualstats_indexes` view was removed in 6619c1090bce and not reflected in README.md?

**Comment by rjuju** [comment]
Indeed, good catch and sorry for missing that.

I fixed it and added documentation for the new other functions in https://github.com/powa-team/pg_qualstats/commit/2faeb3a0dfc6f3765cc1e25c865917aa90880bd4.  Thanks a lot for the report!

**Comment by rom1dep** [comment]
Thanks a lot :)
