### ISSUE TITLE
[Doc] ALTER EXTENSION  UPDATE fails

### ISSUE THREAD

**Issue by Krysztophe** [powa-team/pg_qualstats#34]
There is no SQL scripts, so `ALTER EXTENSION UPDATE` fails:
```
powa=# ALTER EXTENSION pg_qualstats UPDATE;
ERROR: extension "pg_qualstats" has no update path from version "2.0.1" to version "2.0.2"
```
As in https://github.com/HypoPG/hypopg/issues/54, I suppose that it just needs a line about the upgrade in the documentation.

**Comment by rjuju** [comment]
Done in https://github.com/powa-team/pg_qualstats/commit/d8a02123f48c83d89a8d05e069f27c79b5ff7729!

**Comment by Krysztophe** [comment]
Thanks!

**Comment by rjuju** [comment]
As mentioned in https://github.com/HypoPG/hypopg/issues/54 I'm now willing to reconsider this.

I'm keeping this issue opened as a reminder.

**Comment by rjuju** [comment]
I bumped current HEAD to version 2.0.4 and provided an (empty for now) upgrade script.  Version 2.0.4 and later will therefore have an upgrade script.  so I'm closing this issue!
