### ISSUE TITLE
version 2.0.2 has no update path from version "1.0.7" and could not find function "pg_qualstats_2_0" in file 

### ISSUE THREAD

**Issue by banlex73** [powa-team/pg_qualstats#35]
Hello
I have updated binaries to the latest 2.0.2 but couldn't install it on my PG12.5
1. Update failed
`alter extension pg_qualstats update;
ERROR:  extension "pg_qualstats" has no update path from version "1.0.7" to version "2.0.2"
`
2. Create from the scratch failed too
`postgres=# drop extension pg_qualstats;
DROP EXTENSION
postgres=# create extension pg_qualstats;
ERROR:  could not find function "pg_qualstats_2_0" in file "/usr/pgsql-10/lib/pg_qualstats.so"`

**Comment by rjuju** [comment]
Hello,
Indeed pg_qualstats has no upgrade path, like may other extensions.  This isn't required as pg_qualstats doesn't provide any relation that stores data, and not providing an upgrade paths makes the code simpler as it avoids duplicating all the DDL.  I have on my todo list to document this point.

**Comment by rjuju** [comment]
I added the documentation, with some information on the need to restart postgres in https://github.com/powa-team/pg_qualstats/commit/d8a02123f48c83d89a8d05e069f27c79b5ff7729!
