### ISSUE TITLE
PostgreSQL 14 support

### ISSUE THREAD

**Issue by devrimgunduz** [powa-team/pg_qualstats#38]
Hi,

I see that you committed v14 support. This is a placeholder issue for a new release which is v14 compatible.

Thanks!

Devrim

**Comment by rjuju** [comment]
Thanks for the remonder @devrimgunduz .  I just pushed version 2.0.3.!  Let me know if everything is ok.

**Comment by devrimgunduz** [comment]
Thanks @rjuju for quick fix! I'll publish packages soon. Closing this issue.

**Comment by rjuju** [comment]
Thanks a lot @devrimgunduz !
