### ISSUE TITLE
Build fails on Solaris 10 SPARC with Solaris Studio 12.4

### ISSUE THREAD

**Issue by edechaux** [powa-team/pg_qualstats#4]
I want to build pg_qualstats on a Solaris 10 SPARC with Solaris Studio 12.4 and it fails with the following error : 

`bash-3.00$ gmake
/opt/studio11/SUNWspro/bin/cc -Xa -xO3 -xspace -Xa -xildoff -xCC -xarch=generic64 -KPIC -I. -I./ -I/appli/pgsql/9.4.6/include/64/server -I/appli/pgsql/9.4.6/include/64/internal -I/usr/include/libxml2  -I/usr/sfw/include -I/opt/csw/include  -c -o pg_qualstats.o pg_qualstats.c
cc: Warning: -xarch=generic64 is deprecated, use -m64 to create 64-bit programs
"pg_qualstats.c", line 647: invalid cast expression
cc: acomp failed for pg_qualstats.c
gmake: *** [pg_qualstats.o] Error 2`

I am using the master. I have the same error with version 0.0.9 at line 642.
Postgres version is 9.4.6 64 bits

**Comment by rdunklau** [comment]
Hello.

It appears the cast is not necessary. Can you remove it, replacing this line:

		hash_search_with_hash_value(pgqs_query_examples_hash, &entry->key, ((pgqsQueryStringHashKey) entry->key).queryid, HASH_REMOVE, NULL);

By this:

		hash_search_with_hash_value(pgqs_query_examples_hash, &entry->key, entry->key.queryid, HASH_REMOVE, NULL);

Thank you !

**Comment by edechaux** [comment]
Thanks, it works :


`bash-3.00$ gmake
/opt/studio11/SUNWspro/bin/cc -Xa -xO3 -xspace -Xa -xildoff -xCC -xarch=generic64 -KPIC -I. -I./ -I/appli/pgsql/9.4.6/include/64/server -I/appli/pgsql/9.4.6/include/64/internal -I/usr/include/libxml2  -I/usr/sfw/include -I/opt/csw/include  -c -o pg_qualstats.o pg_qualstats.c
cc: Warning: -xarch=generic64 is deprecated, use -m64 to create 64-bit programs
/opt/studio11/SUNWspro/bin/cc -Xa -xO3 -xspace -Xa -xildoff -xCC -xarch=generic64 -KPIC -L/appli/pgsql/9.4.6/lib/64 -L/usr/lib  -L/usr/sfw/lib/64 -L/opt/csw/lib/64 -Wl,-R'/appli/pgsql/9.4.6/lib/64'  -G -o pg_qualstats.so pg_qualstats.o
cc: Warning: -xarch=generic64 is deprecated, use -m64 to create 64-bit programs`

**Comment by rjuju** [comment]
I integrated this change in the tree, in case someone else face this issue.
