### ISSUE TITLE
ERROR:  there is no parameter $1 when i try execute the function.

### ISSUE THREAD

**Issue by fernandorb10** [powa-team/pg_qualstats#52]
Hi. any idea for this error? thanks.

select find_usable_indexes();
NOTICE:  relation "idx_recommendations" already exists, skipping
ERROR:  there is no parameter $1
LINE 1: ...SION tokensessi0_ where tokensessi0_.SIGNATURE_ID=$1 and tok...

**Comment by rjuju** [comment]
Hi,

I don't know what "find_usable_indexes()" is, there's no such function in pg_qualstats.  Whatever that function is, it seems that it needs to be taught about how pg_stat_statements normalizes queries or something like that.

**Comment by rjuju** [comment]
On a side note, if you're looking for an index advisor, pg_qualstats has one included since [version 2.0.0](https://github.com/powa-team/pg_qualstats/releases/tag/2.0.0).

See https://rjuju.github.io/postgresql/2020/01/06/pg_qualstats-2-global-index-advisor.html for more details on how it works.

**Comment by fernandorb10** [comment]
Oh sorry, I had seen the function in a percona blog and thought it was specific to the extension.
