### ISSUE TITLE
PG15 binary for Windows

### ISSUE THREAD

**Issue by Raniz85** [powa-team/pg_qualstats#55]
Release notes for 2.0.4 states that support for PostgreSQL 15 has been added, but the release does not contain any .exe/zip for PG15 on Windows.

**Comment by rjuju** [comment]
Hi,

Yes that's because I didn't have postgres 15 installed on my windows packaging machine when I did the release.  That's fixed now, I just uploaded the artifacts for pg15.

**Comment by Raniz85** [comment]
Wow, that was quick!

Thanks a lot!
