### ISSUE TITLE
PG16 binary for Windows

### ISSUE THREAD

**Issue by sviams** [powa-team/pg_qualstats#58]
Hi, would it be possible to include a binary for PG16 for Windows? Would be much appreciated! Thanks

**Comment by rjuju** [comment]
Hi,

I just added windows installers and zip archives for pg_qualstats 2.1.0 on pg  9,5 to 16!  Available on the release: https://github.com/powa-team/pg_qualstats/releases/tag/2.1.0

**Comment by sviams** [comment]
You sir, are an absolute legend.

**Comment by rjuju** [comment]
Thanks a lot :)
