### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devrimgunduz** [powa-team/pg_qualstats#63]
Hi,

Latest release does not compile against v17. I see that you committed fixes for it. Can you please release a new version so that I can build the RPMs? GA is due soon.

Thanks! Devrim

**Comment by devrimgunduz** [comment]
ping

**Comment by rjuju** [comment]
I will take care of it this weekend

**Comment by devrimgunduz** [comment]
Thanks, but v17.0 is due tomorrow :(

**Comment by rjuju** [comment]
I just pushed a new tag, I will take cake of the rest of the process this weekend.

**Comment by devrimgunduz** [comment]
@rjuju appreciated. Thanks!
